logfile_info: '1226-FedAvg_PathMNIST_20Clients_alpha0.01'
wandb_project: '20231224'
num_clients: 20
wandb: 1

dirichlet_alpha: 0.01

# client_dataset: 'emnist'  
# num_class: 47  

client_dataset: 'PathMNIST'
num_class: 9

# client_dataset: 'cifar100'
# num_class: 100
