logfile_info: '20231104(01)'
client_dataset: 'cifar10'
server_dataset: 'cifar100'
st_weight: 0.5

num_clients: 10
batch_size: 32 
dirichlet_alpha: 0.1
model_type: 'resnet18'
round: 10
num_class: 10
client_model: 'resnet18'
server_model: 'resnet50'
local_epoch: 15
seed: 42
device: 'cuda'
client_resource: {"num_gpus": 1, "num_cpus": 4}

distill_epoch: 15
dataset_path: "../dataset"
wandb_project: '20231104'
distill_lr: 0.001
use_softmax_to_distill: 0
wandb: 1
save_client_model: 0


