logfile_info: '0'
wandb_project: '0'
wandb: 1
client_dataset: '0'
num_class: 0

num_clients: 1
batch_size: 64
dirichlet_alpha: 0
model_name: 'ViT-B/32'
# RN50 RN101 RN50x4 ViT-B/32 ViT-B/16 BLIP-base ALBEF-base

round: 40

device: 'cuda'

dataset_path: "../dataset"
save_client_model: 0

margin: 0.2
local_lr: 0
local_momentum: 0.9
local_weight_decay: 1e-4
local_epoch: 100
use_mlp: 1

use_softmax: 0

use_before_fc_emb: 0



reverse_textemb: 0
mlp_hiddenlayer_num: 2048

use_timm: 0
only_test_training_labels: 0

select_client_num: 0
use_privacy_generator: 0

strategy: 'FedAL'
meaningful_anchor: 0


