logfile_info: '0'
wandb_project: '0'
num_clients: 20
select_client_num: 15
wandb: 1

# dirichlet_alpha: 0.01

strategy: 'FedAvg'
# local_lr: 0.01

model_name: 'ViT-B32-timm'

# ============================================================================ #
# Dataset

# client_dataset: 'emnist'  

# client_dataset: 'PathMNIST'

