logfile_info: '1227-PathMNIST_20Clients_Alpha0.1_LR0.001_NoBefore'
wandb_project: '20231227EMNIST'
num_clients: 20
wandb: 1

dirichlet_alpha: 0.1
local_lr: 0.001

client_dataset: 'emnist'  

# client_dataset: 'PathMNIST'

# client_dataset: 'cifar100'


use_before_fc_emb: 0


