
num_clients: 20
select_client_num: 15
wandb: 1


client_dataset: 'cifar100'  

# client_dataset: 'PathMNIST'

# client_dataset: 'cifar100'


gene_num: 5000
model_name: 'ViT-B/32'  # ViT-B32-timm, ViT-B/32

meaningful_anchor: 1
gpt3_anchor: 'no' # ensembel_prompt, one_prompt, no, description, description_dim3072

local_epoch: 100
round: 40
