logfile_info: 'test'
client_dataset: 'cifar10'
server_dataset: 'cifar10'
st_weight: 1

num_clients: 4
batch_size: 32 
dirichlet_alpha: 0.1
round: 1
num_class: 10
client_model: 'resnet18'
server_model: 'resnet50'
local_epoch: 1
seed: 42
device: 'cuda'
client_resource: {"num_gpus": 1, "num_cpus": 4}

distill_epoch: 2
dataset_path: "../dataset"
wandb_project: '20231104'
distill_lr: 0.001
use_softmax_to_distill: 0
wandb: 0



