logfile_info: 'test(01)'
wandb_project: 'test'
wandb: 0

num_clients: 4
batch_size: 64
dirichlet_alpha: 0.1
model_name: 'ViT-B/32'
mlp_hiddenlayer_num: 2048
client_dataset: 'PathMNIST'
# RN50 RN101 RN50x4 ViT-B/32 ViT-B/16

round: 3
device: 'cuda'
dataset_path: "../dataset"
save_client_model: 0

margin: 0.2
local_lr: 0.001
local_momentum: 0.9
local_weight_decay: 1e-4
local_epoch: 1
use_mlp: 0



use_before_fc_emb: 1  # 1 or 0
gene_num: 1000
use_before_fc_emb_round: 1  # Minimum is 1




