logfile_info: '1224-emnist_20Clients_alpha0.5_NoBefore'
wandb_project: '20231224'
num_clients: 20

dirichlet_alpha: 0.5

client_dataset: 'emnist'  # cifar100
num_class: 47  # 100

# client_dataset: 'PathMNIST'
# num_class: 9


use_before_fc_emb: 0


