logfile_info: '1209-C100-usemlp_OnlyGen_Gen2W_E50_BeforeEmbStart1'
wandb_project: '20231209'


num_clients: 10

client_dataset: 'cifar100'
num_class: 100

reverse_textemb: 1

local_epoch: 50
use_mlp: 1
round: 80

use_before_fc_emb: 1
gene_num: 20000
use_before_fc_emb_round: 1

use_traditional_loss_lower_limit: 0
use_traditional_loss_upper_limit: 2
