logfile_info: '1207-C100_useBeforeStart1'
wandb_project: '20231207WithEpoch'

use_after_fc_emb: 0

use_before_fc_emb: 1  # 1 or 0
gene_num: 10000
use_before_fc_emb_round: 1  # Minimum is 1
more_dense: 10



use_softmax: 0
margin: 0.2
client_dataset: 'cifar100'

num_class: 100
round: 1000
use_mlp: 0
